name: 'Common Steps'
description: 'Checkout and Install Dependencies'

runs:
  using: "composite"
  steps:
    - name: Get Code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci