name: Test Project
on: [push, workflow_dispatch]
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
  run-lint:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Run Lint
        run: npm run lint
  run-test:
    needs: [run-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: npm test
  build-project:
    needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: npm run build
