name: Test Project
on: [push]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/actions/my-common-steps
      - name: Run Lint
        run: npm run lint
  run-test:
    needs: [run-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/actions/my-common-steps
      - name: Run test
        run: npm test
  build-project:
    needs: [run-test]
    runs-on: ubuntu-latest
    steps:
      - name: Common Steps
        uses: ./.github/actions/my-common-steps
      - name: Build Project
        run: npm run build
